### ISSUE TITLE
Récupérer les mots du dictionnaire depuis Podle vers le BO

### ISSUE THREAD

**Issue by ThomSawyer** [briefmnews/django-podle#2]

**Comment by eespanel** [comment]
Suite à notre discussion, j'ai renommer le ticket : Récupérer les mots du dictionnaire depuis Podle vers le BO.
La rédaction fera désormais tout podle dans le dictionnaire de Podle, il sont ont tout en un point comme ça. 
On fera évoluer autrement si besoin.

**Comment by ThomSawyer** [comment]
abandonné
